// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djecsmgcrkvkqgbjuiqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZWNzbWdjcmt2a3FnYmp1aXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzg0ODYsImV4cCI6MjA2ODkxNDQ4Nn0.V0sPqrIsWTriZ2-ph-Rq6E5czNIOD72BQ_IKELeSH0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});